name: Build EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter cryptography

    - name: Build Store EXE
      run: |
        pyinstaller --noconsole --onefile main.py

    - name: Build Keygen EXE
      run: |
        pyinstaller --noconsole --onefile keygen.py

    - name: Upload Store Artifact
      uses: actions/upload-artifact@v4
      with:
        name: App-Store-EXE
        path: dist/main.exe

    - name: Upload Keygen Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Key-Generator-EXE
        path: dist/keygen.exe
